apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chronocanvas
  annotations:
    cloud.google.com/backend-config: '{"default": "chronocanvas-backend-config"}'
  labels:
    app.kubernetes.io/part-of: chronocanvas
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/part-of: chronocanvas
    app.kubernetes.io/component: frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  # NodePort is required for GKE native Ingress (Cloud Load Balancer)
  type: NodePort
