apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: chronocanvas
  labels:
    app.kubernetes.io/part-of: chronocanvas
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/part-of: chronocanvas
    app.kubernetes.io/component: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
