apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: chronocanvas
  labels:
    app.kubernetes.io/part-of: chronocanvas
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: chronocanvas
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: chronocanvas
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - --maxmemory
            - 128mb
            - --maxmemory-policy
            - allkeys-lru
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "128Mi"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
