apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronocanvas-sa
  namespace: chronocanvas
  annotations:
    # Uncomment and set when upgrading to Workload Identity for Cloud SQL / Secret Manager
    # iam.gke.io/gcp-service-account: chronocanvas@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/part-of: chronocanvas
